### PR TITLE
17.6 Valkiria

### PR DESCRIPTION
**Pull request by giocap73**

### CODE REVIEW

**Comment by oberon2007** [comment]
Next letter in alphabet will be **H** not **V*, sorry! :nerd_face:

**Comment by giocap73** [comment]
17.6 Hellenic

**Comment by oberon2007** [comment]
not bad already! :+1: 
@philmmanjaro already might have something in mind, also :)

**Comment by philmmanjaro** [comment]
Names can be found [here](https://github.com/manjaro/release-plan/blob/master/codenames.md).

**Pull request closed without merging**
